### ISSUE TITLE
大佬能发布个版本到nuget上给我们用吗？

### ISSUE THREAD

**Issue by weibinlong** [EasyAbp/Abp.DynamicQuery#2]

**Comment by wakuflair** [comment]
This repo is under development, and not ready for publishing packages.

**Comment by gdlcf88** [comment]
@weibinlong Please transfer these NuGet packages to user `EasyAbp`:
[EasyAbp.Abp.DynamicQuery.Application](https://www.nuget.org/packages/EasyAbp.Abp.DynamicQuery.Application)
[EasyAbp.Abp.DynamicQuery.Application.Contracts](https://www.nuget.org/packages/EasyAbp.Abp.DynamicQuery.Application.Contracts)
[EasyAbp.Abp.DynamicQuery.Domain](https://www.nuget.org/packages/EasyAbp.Abp.DynamicQuery.Domain)
[EasyAbp.Abp.DynamicQuery.Domain.Shared](https://www.nuget.org/packages/EasyAbp.Abp.DynamicQuery.Domain.Shared)
[EasyAbp.Abp.DynamicQuery.EntityFrameworkCore](https://www.nuget.org/packages/EasyAbp.Abp.DynamicQuery.EntityFrameworkCore)

![image](https://user-images.githubusercontent.com/30018771/130207147-aef5e320-f7d5-40e0-925f-f2e06d16cd2e.png)

Thank you for your contribution to EasyAbp.
